engines:
  fixme:
    enabled: true
  eslint:
    enabled: true
    channel: "eslint-3"
  markdownlint:
    enabled: true

ratings:
  paths:
    - "**.js"
    - "**.ts"
    - "README.md"

exclude_paths:
  - ".idea/"
  - ".git/"
  - "node_modules/"
  - "coverage/"
  - "dist/"
  - "scripts/"
  - "karma.conf.js"
  - "src/webpack-bundle.config.js"
