language: node_js
sudo: required
dist: trusty
node_js:
  - '6.6.0'

addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
      - google-chrome-beta

cache:
  directories:
     - ./node_modules
     - ./.chrome/chromium

before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

before_script:
- npm install -g angular-cli
- npm install -g karma
- npm install

script: karma start karma.conf.js --single-run
