language: node_js
sudo: required
dist: trusty
node_js:
  - '6.6.0'

branches:
  only:
    - master

addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
      - google-chrome-beta

cache:
  directories:
    - $HOME/.chrome/chromium
    - node_modules

addons:
    code_climate: {}

before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - npm install --cache-min Infinity --spin false --progress false --no-optional -g npm
  - npm install --cache-min Infinity --spin false --progress false --no-optional -g karma codeclimate-test-reporter

install:
  - npm install --cache-min Infinity --spin false --progress false --no-optional

script: karma start karma.conf.js --single-run

after_script:
  - node scripts/fix-codeclimate-lcov.js < coverage/coverage.lcov | codeclimate-test-reporter

