language: node_js
sudo: required
dist: trusty
node_js:
  - '6.6.0'

branches:
  only:
    - master

addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
      - google-chrome-beta

cache:
  directories:
#     - ./node_modules
     - ./.chrome/chromium
addons:
    code_climate: {}

before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - npm config set spin false
  - npm config set progress false
  - npm config set cache-min Infinity
  - npm install -g npm
  - npm install -g yarn
  - yarn global add --flat ignore-optional karma
  - yarn global add --flat ignore-optional codeclimate-test-reporter

install:
  - yarn global add ignore-optional

script: karma start karma.conf.js --single-run

after_script:
  - node scripts/fix-codeclimate-lcov.js < coverage/coverage.lcov | codeclimate-test-reporter

