language: node_js
sudo: required
dist: trusty
node_js:
  - '6.6.0'

branches:
  only:
    - master

addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
      - google-chrome-beta

cache:
  directories:
    - $HOME/.yarn-cache
    - ./.chrome/chromium
#     - ./node_modules
addons:
    code_climate: {}

before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - npm install -g github:yarnpkg/yarn --cache-min Infinity --spin false --progress false
  - yarn global add --ignore-optional karma
  - yarn global add --ignore-optional codeclimate-test-reporter

install:
  - yarn --ignore-optional

script: karma start karma.conf.js --single-run

after_script:
  - node scripts/fix-codeclimate-lcov.js < coverage/coverage.lcov | codeclimate-test-reporter

